[project]
name = "fontbakery"
version = "1.2.0"
description = "A font quality assurance tool for everyone"
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.13"
authors = [
  { name = "Chris Simpkins", email = "csimpkins@google.com" },
  { name = "Dave Crossland", email = "dcrossland@google.com" },
  { name = "Felipe Sanches", email = "juca@members.fsf.org" },
  { name = "Jens Kutilek" },
  { name = "Lasse Fister" },
  { name = "Marc Foley" },
  { name = "Miguel Sousa" },
  { name = "Nikolaus Waxweiler" },
  { name = "Rosalie Wagner" },
  { name = "Simon Cozens" },
  { name = "Vitaly Volkov" },
  { name = "Viviana Monsalve" },
  { name = "Yanone" },
]
maintainers = [
  { name = "Jens Kutilek", email = "webmail@kutilek.de" },
]

dependencies = [
  "Jinja2 >= 3.1.6",  # issue #4717
  "PyYAML",
  "beziers >= 0.6.0, == 0.6.*",
  "cmarkgfm >= 2025.10.22",
  "defcon",
  "dehinter >= 4.0.0",  # 3.1.0 added dehinter.font.hint function
  "fontTools[ufo] >= 4.64.0",  # varLib.interpolatableHelpers.InterpolatableProblem
  "freetype-py < 2.6.0",  # see: https://github.com/fonttools/fontbakery/issues/4143
  "munkres",
  "opentypespec >= 1.9.2",  # recognize 'sunu' script tag for Sunuwar (fontbakery/issues/5014)
  "packaging >= 26.3",  # VERSION_PATTERN was added on v14.5 (fontbakery/issues/4792)
  "pip-api",
  "pyots >= 9.3.0, == 9.*",
  "requests >= 2.34.2",
  "rich",
  "toml",
  "ufo2ft >= 3.9.0",  # script lists for Unicode 14.0 were updated on v2.25.2
  "ufolint",
  "uharfbuzz",
  "vharfbuzz >= 0.3.1",
]

[project.scripts]
fontbakery = "fontbakery.cli:main"

[project.optional-dependencies]
# Note: These dependencies are meant to be private (not used explicitly by users)
#       and are used just to facilitate maintainance of versioning
#       dependencies that are shared by multiple vendor-profiles.
#       (this way, the maintainer only needs to edit a single entry)

beautifulsoup4 = [
  "beautifulsoup4 >= 4.15.0",
  # For parsing registered vendor IDs
  # googlefonts/vendor_id produces an ERROR if Beautiful Soup 4
  # version 4.0.1 to 4.6.1 or 4.7.0 is installed because of bugs in Beautiful Soup
  # (see https://github.com/fonttools/fontbakery/issues/4270)
]

shaperglot = [
  "shaperglot >= 1.2.1, == 1.*",
]

# These Google Fonts profile dependencies contain data that is critical to
# always be up-to-date, so we treat any update to these deps the same way we would
# deal with API-breaking updates. Only the latest released version is acceptable:
googlefontsalwayslatest = [
  "axisregistry >= 0.4.16, == 0.4.*",
  "gflanguages >= 0.7.7, == 0.7.*",
  "gfsubsets >= 2025.11.4",
  "glyphsets >= 1.1.0, == 1.*",
  "shaperglot >= 1.2.1, == 1.*",
]

# Profile-specific dependencies:

adobefonts = [
  # The Adobe Fonts profile currently depends only on the base-install of
  # fontbakery dependencies. But we keep here a place-holder "extra" for
  # consistency (all vendor-specific profiles have the same install instructions)
  # And at some point in the future there may be actual dependencies listed
  # here for this profile.
]

fontval = [
  "lxml",
]

fontwerk = [
  "fontbakery[googlefonts]",
]

googlefonts = [
  "collidoscope >= 0.5.2",
  # 0.5.2 added Python 3.11 wheels
  # (see https://github.com/fonttools/fontbakery/issues/3970)

  "fonttools[lxml,unicode]",
  # (see https://github.com/googlefonts/gflanguages/pull/7)

  "protobuf >= 3.7.0, < 4",
  # 3.7.0 fixed a bug on parsing some METADATA.pb files.
  # We cannot use v4 because our protobuf files have been compiled with v3.
  # (see https://github.com/fonttools/fontbakery/issues/2200)

  "stringbrewer",

  "unicodedata2",

  "fontbakery[beautifulsoup4]",
  "fontbakery[googlefontsalwayslatest]",
  "fontbakery[shaperglot]",
]

iso15008 = []

microsoft = []

notofonts = [
  "fontbakery[googlefonts]",
]

typenetwork = [
  "unicodedata2",

  "fontbakery[beautifulsoup4]",
  "fontbakery[shaperglot]",
]

# Some users may want a full install of all profiles:

all = [
  "fontbakery[adobefonts]",
  "fontbakery[fontval]",
  "fontbakery[fontwerk]",
  "fontbakery[googlefonts]",
  "fontbakery[iso15008]",
  "fontbakery[notofonts]",
  "fontbakery[typenetwork]",
]

[dependency-groups]
dev = [
  "fontbakery[all]",
  "mypy >= 2.3.1",
  "ruff >= 0.16.5",
  "types-jsonschema >= 4.26.0.20260518",
  "types-python-dateutil >= 2.9.0.20260807",
  "types-pyyaml >= 6.0.12.20260815",
]
doc = [
  "m2r >= 0.3.1",
  "myst-parser >= 2.0.0",
  "sphinx_rtd_theme >= 3.1.0",
  "sphinx >= 9.1.0",
]
test = [
  "pytest-cov >= 7.1.0",
  "pytest >= 9.1.1",
  "requests_mock >= 1.12.1",
  "tox-gh >= 1.8.0",
  "tox-uv >= 1.36.0",
  "tox >= 4.61.2",
  { include-group = "dev" },
]

[build-system]
requires = ["uv_build>=0.12.8,<0.13"]
build-backend = "uv_build"

[tool.pytest.ini_options]
cache_dir = "build/tests/pytest_cache"
# addopts = "--mypy --pylint --black --isort --cov --cov-report=term --cov-report=html --cov-report=xml"
# "src" required for pylint and mypy (whereas cov considers imported files):
testpaths = ["tests", "src"]

[tool.ruff]
extend-exclude = [
  "*_pb2.py",
  "Lib/fontbakery/prelude.py",
]

[tool.ruff.lint]
future-annotations = false
ignore = ["N999"]

[tool.ruff.lint.isort]
known-first-party = ["lfFontTools"]

[tool.uv.build-backend]
# data = { data = "schema/*.yaml"}
module-name = "fontbakery"
