name: 🧑‍🔬 Lint & Test

on:
  push:
    branches:
      - "**"
    paths-ignore:
      - "docs/**"
      - "**.md"
      - "**.txt"
      - "!requirements*.txt"
    tags-ignore:
      - "**"

  pull_request:
    paths-ignore:
      - "docs/**"
      - "**.md"
      - "**.txt"
      - "!requirements*.txt"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.13", "3.14", "3.15"]

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0 # unshallow fetch for setuptools-scm (otherwise the version is always 0.1.dev1)

      - name: Set up Python ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@v10.2.0
        with:
          python-version: ${{ matrix.python }}

      - name: Install the project with test dependencies
        run: uv sync --locked --group test

      - name: Install tox
        run: uv tool install tox --with tox-uv --with tox-gh

      - name: Run test suite
        run: uv run tox --skip-pkg-install
        env:
          TOX_GH_MAJOR_MINOR: ${{ matrix.python }}

      - name: Ensure documentation can build (only Ubuntu/Python 3.10)
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.10'
        run: |
          cd docs; make html
